services:
  qdrant:
    image: qdrant/qdrant:v1.11.3
    container_name: qdrant
    ports:
      - "6333:6333"  # Porta padrão para a API REST do Qdrant
    volumes:
      - qdrant_storage:/qdrant/storage  # Persistência de dados
    environment:
      QDRANT__LOG_LEVEL: "INFO"  # Define o nível de log
      QDRANT__SERVICE__HTTP_PORT: 6333  # Porta para a API HTTP
      QDRANT__STORAGE__DISK_THRESHOLD: 0.9  # Limite de utilização de disco antes do aviso (90%)

volumes:
  qdrant_storage:
    driver: local